name: Enactus uOttawa
favicon: null
layout_spectrum: 0.8971742943394929
typography_spectrum: 0.2724144358653575
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#E0FBFC'
    - '#C2DFE3'
    - '#9DB4C0'
    - '#5C6B73'
    - '#253237'
  brandStrength: 0.8135825004428625
  lightness: 0.40611306647770107
  saturation: 0.12368685007095337
  rhythmicContrast: 0.9805734599940479
purpose: []
