name: Enactus uOttawa
favicon: null
layout_spectrum: 1
typography_spectrum: 0.82039
title: 'Enactus uOttawa | Student social entrepreneurs igniting change within communities'
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#515356'
    - '#f3bd4a'
    - '#000000'
    - '#919091'
    - '#ffffff'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.12368685007095337
  rhythmicContrast: 1
purpose: []
